services:
    github-contributions:
        image: pumbas600/github-contributions:latest
        ports:
            - '3000:3000'
        env_file:
            - .env.local
        mem_limit: 400mb
        memswap_limit: 400mb
        restart: on-failure:3
